## FP: Biodiversity of the National Production through Companion Plants Analysis

Authors:

    Astrid Monserrat Rivera Partida     A01324504
    Diego Concepción Villatoro Gerónimo A01328525

### Summary

The world population increases at an accelerated pace, and it is essential to find solutions to feed the population. Nevertheless, crop diversity has significantly decreased in the last years, and the increase in food production is not the optimal solution. It is essential to consider the origin of the food, the nutriment contributions, among other dimensions. In this regard, biodiversity plays an indispensable role when designing an effective strategy to face the actual food security problems. Consequently, the purpose of this work is to analyze biodiversity in the national food production and suggest a proper crop selection based on companion plants, for which empirical and experimental knowledge shows a better scenery than current efforts. We need to explore more feasible options to advance sustainable development goals beyond an economic aspect.


First of all importing all libraries

In [1]:
"""Data Preparation Library"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
#Read data for Mexico in 2019

df = pd.read_csv("FAOSTAT.csv")
#df = pd.read_csv("crops.csv")

pd.set_option('display.max_columns', None)

df

,Area,Item,Year,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
0,Mexico,Agave fibres nes,2019,22104.0,6028.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mexico,"Almonds, with shell",2019,27.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mexico,"Anise, badian, fennel, coriander",2019,7099.0,100560.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mexico,Apples,2019,52981.0,761483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mexico,Apricots,2019,185.0,967.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Mexico,Vetches,2019,7774.0,97230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,Mexico,"Walnuts, with shell",2019,102068.0,171368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Mexico,Watermelons,2019,39347.0,1345705.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Mexico,Wheat,2019,586543.0,3244062.0,340.0,13.21,72.0,2.5,10.7,9.0,1.9,NaN,5.0,44.0,34.0,3.6,363.0,137.0,357.0,2.0,2.6,61.8,4.06,64.0,0.175342
111,Mexico,Yautia (cocoyam),2019,482.0,36128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
null_Data = pd.DataFrame(df.isnull().sum(),columns=["Count"])
pd.set_option('display.max_rows', 90)
null_Data["Count"]

Area                              0
Item                              0
Year                              0
Area harvested (ha)               1
Production (tonnes)               1
Calories (100gr)                 94
Protein                          94
Carbohydrates                    94
Fats                             94
Fiber                            94
Vitamin A                        96
Vitamin K                       100
Vtamin C                        100
Vitamin B-3                     105
Vitamin B-9                      94
Calcium                          94
Iron                            105
Potasium                         94
Magnesium                        94
phosphorus                       94
Sodium                           96
Zinc                            107
Selenium                        106
Manganese                       109
Annual Consumption Percapita    101
Daily Consuption Percapita       94
Name: Count, dtype: int64

## Arrange dataset from FAOSTAT

In [5]:
df.drop(columns = ['Area'], inplace=True)
df.drop(columns = ['Year'], inplace=True)
df

,Item,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
0,Agave fibres nes,22104.0,6028.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Almonds, with shell",27.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Anise, badian, fennel, coriander",7099.0,100560.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apples,52981.0,761483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Apricots,185.0,967.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Vetches,7774.0,97230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,"Walnuts, with shell",102068.0,171368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Watermelons,39347.0,1345705.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Wheat,586543.0,3244062.0,340.0,13.21,72.0,2.5,10.7,9.0,1.9,NaN,5.0,44.0,34.0,3.6,363.0,137.0,357.0,2.0,2.6,61.8,4.06,64.0,0.175342
111,Yautia (cocoyam),482.0,36128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For getting the companion plants we use GEPHI software using the files node.csv and edge.csv and making a filter of the nodes to get the top 10 of the more interrelated plants, which are the seek in the next part.

### Top 10 of the best companion plant in the national production

We look for the 10 more interrelated companion plants in the national production

In [6]:
cropReccomendation = ["Potatoes", "Nasturtiums", "Marigold", "Marjoram", "Lettuce", "Cucumber", "Beans", "Cabbages", "Tomatoes", "Carrots"]
dfCompanionTop10 = df[(df['Item'].str.contains(cropReccomendation[0])) | (df['Item'].str.contains(cropReccomendation[1])) | (df['Item'].str.contains(cropReccomendation[2])) | (df['Item'].str.contains(cropReccomendation[3])) | (df['Item'].str.contains(cropReccomendation[4])) | (df['Item'].str.contains(cropReccomendation[5])) | (df['Item'].str.contains(cropReccomendation[6]) | (df['Item'].str.contains(cropReccomendation[7]))) | (df['Item'].str.contains(cropReccomendation[8])) | (df['Item'].str.contains(cropReccomendation[9]))]
dfCompanionTop10

,Item,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
10,"Beans, dry",1207395.0,879404.0,71.0,4.07,13.3,0.0,3.6,150.0,NaN,7.3,NaN,16.0,28.0,1.61,285.0,34.0,71.0,252.0,NaN,1.1,NaN,10.2,0.027945
11,"Beans, green",8458.0,81161.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Cabbages and other brassicas,6115.0,203986.0,25.0,1.28,5.8,0.0,2.5,98.0,76.0,36.6,NaN,43.0,40.0,NaN,170.0,12.0,26.0,18.0,NaN,NaN,NaN,NaN,0.000000
18,Carrots and turnips,11750.0,353750.0,41.0,0.00,9.6,0.0,2.8,16706.0,13.2,5.9,1.0,19.0,33.0,NaN,320.0,12.0,35.0,69.0,NaN,NaN,NaN,NaN,0.000000
32,Cucumbers and gherkins,16115.0,826485.0,15.0,0.00,3.6,0.0,0.0,105.0,16.4,2.8,NaN,7.0,16.0,NaN,147.0,13.0,24.0,2.0,NaN,NaN,NaN,1.6,0.004384
48,Lettuce and chicory,20778.0,515647.0,13.0,1.35,2.2,0.0,1.1,3312.0,102.3,3.7,NaN,73.0,35.0,1.24,238.0,13.0,33.0,5.0,NaN,NaN,NaN,2.5,0.006849
76,Potatoes,58442.0,1783896.0,77.0,2.02,17.5,0.0,2.2,2.0,1.9,19.7,1.1,16.0,12.0,NaN,421.0,23.0,57.0,6.0,NaN,NaN,NaN,14.8,0.040548
102,Tomatoes,87917.0,4271914.0,23.0,1.20,5.1,0.0,1.1,642.0,10.1,23.4,NaN,9.0,13.0,NaN,204.0,10.0,28.0,13.0,NaN,NaN,NaN,15.2,0.041644

We remove the "Beans, green" item because it does not allow to the top 10 of companion plants

In [7]:
dfCompanionTop10 = dfCompanionTop10.drop(11)
dfCompanionTop10

,Item,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
10,"Beans, dry",1207395.0,879404.0,71.0,4.07,13.3,0.0,3.6,150.0,NaN,7.3,NaN,16.0,28.0,1.61,285.0,34.0,71.0,252.0,NaN,1.1,NaN,10.2,0.027945
15,Cabbages and other brassicas,6115.0,203986.0,25.0,1.28,5.8,0.0,2.5,98.0,76.0,36.6,NaN,43.0,40.0,NaN,170.0,12.0,26.0,18.0,NaN,NaN,NaN,NaN,0.000000
18,Carrots and turnips,11750.0,353750.0,41.0,0.00,9.6,0.0,2.8,16706.0,13.2,5.9,1.0,19.0,33.0,NaN,320.0,12.0,35.0,69.0,NaN,NaN,NaN,NaN,0.000000
32,Cucumbers and gherkins,16115.0,826485.0,15.0,0.00,3.6,0.0,0.0,105.0,16.4,2.8,NaN,7.0,16.0,NaN,147.0,13.0,24.0,2.0,NaN,NaN,NaN,1.6,0.004384
48,Lettuce and chicory,20778.0,515647.0,13.0,1.35,2.2,0.0,1.1,3312.0,102.3,3.7,NaN,73.0,35.0,1.24,238.0,13.0,33.0,5.0,NaN,NaN,NaN,2.5,0.006849
76,Potatoes,58442.0,1783896.0,77.0,2.02,17.5,0.0,2.2,2.0,1.9,19.7,1.1,16.0,12.0,NaN,421.0,23.0,57.0,6.0,NaN,NaN,NaN,14.8,0.040548
102,Tomatoes,87917.0,4271914.0,23.0,1.20,5.1,0.0,1.1,642.0,10.1,23.4,NaN,9.0,13.0,NaN,204.0,10.0,28.0,13.0,NaN,NaN,NaN,15.2,0.041644

### Top 10 of the crops with the major production

We sort the values for the production in tonnes

In [8]:
dfTop10 = df.sort_values(by=['Production (tonnes)'], ascending=False)[0:10]
dfTop10

,Item,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
97,Sugar cane,795984.0,59334059.0,380.0,0.00,98.1,0.00,0.0,NaN,NaN,NaN,NaN,1.0,83.0,NaN,133.0,9.0,4.0,28.0,1.20,1.2,NaN,NaN,0.000000
50,Maize,6690449.0,27228242.0,365.0,9.42,74.3,4.74,7.3,214.0,NaN,NaN,3.6,19.0,7.0,2.71,287.0,127.0,210.0,35.0,2.21,15.5,NaN,336.6,0.922192
64,Oranges,329561.0,4736715.0,47.0,0.00,11.8,0.00,2.4,225.0,NaN,53.2,NaN,30.0,40.0,NaN,181.0,10.0,14.0,NaN,NaN,NaN,NaN,37.0,0.101370
90,Sorghum,1324783.0,4352947.0,329.0,10.62,72.1,3.46,6.7,NaN,NaN,NaN,3.7,20.0,13.0,3.36,363.0,165.0,289.0,2.0,1.67,12.2,1.60,NaN,0.000000
102,Tomatoes,87917.0,4271914.0,23.0,1.20,5.1,0.00,1.1,642.0,10.1,23.4,NaN,9.0,13.0,NaN,204.0,10.0,28.0,13.0,NaN,NaN,NaN,15.2,0.041644
110,Wheat,586543.0,3244062.0,340.0,13.21,72.0,2.50,10.7,9.0,1.9,NaN,5.0,44.0,34.0,3.60,363.0,137.0,357.0,2.0,2.60,61.8,4.06,64.0,0.175342
27,"Chillies and peppers, green",149577.0,3238245.0,27.0,0.00,4.7,0.00,2.6,1700.0,12.9,10.0,NaN,14.0,23.0,1.88,193.0,15.0,18.0,1671.0,NaN,NaN,NaN,18.1,0.049589
46,Lemons and limes,183575.0,2701828.0,29.0,1.10,9.3,0.00,2.8,22.0,NaN,53.0,NaN,11.0,26.0,NaN,138.0,8.0,16.0,2.0,NaN,NaN,NaN,14.5,0.039726
52,"Mangoes, mangosteens, guavas",215982.0,2396675.0,60.0,0.00,15.0,0.00,1.6,1082.0,4.2,36.4,NaN,43.0,11.0,NaN,168.0,10.0,14.0,1.0,NaN,NaN,NaN,NaN,0.000000
7,Avocados,215942.0,2300889.0,160.0,2.00,8.5,14.66,6.7,146.0,21.0,10.0,1.7,81.0,12.0,NaN,485.0,29.0,52.0,7.0,NaN,NaN,NaN,8.0,0.021918

### Top 10 of the crops with the major harvested area

We sort the values for the harvested area in ha.

In [9]:
dfTop10 = df.sort_values(by=['Area harvested (ha)'], ascending=False)[0:10]
dfTop10

,Item,Area harvested (ha),Production (tonnes),Calories (100gr),Protein,Carbohydrates,Fats,Fiber,Vitamin A,Vitamin K,Vtamin C,Vitamin B-3,Vitamin B-9,Calcium,Iron,Potasium,Magnesium,phosphorus,Sodium,Zinc,Selenium,Manganese,Annual Consumption Percapita,Daily Consuption Percapita
50,Maize,6690449.0,27228242.0,365.0,9.42,74.3,4.74,7.3,214.0,NaN,NaN,3.6,19.0,7.0,2.71,287.0,127.0,210.0,35.0,2.21,15.5,NaN,336.6,0.922192
90,Sorghum,1324783.0,4352947.0,329.0,10.62,72.1,3.46,6.7,NaN,NaN,NaN,3.7,20.0,13.0,3.36,363.0,165.0,289.0,2.0,1.67,12.2,1.60,NaN,0.000000
10,"Beans, dry",1207395.0,879404.0,71.0,4.07,13.3,0.00,3.6,150.0,NaN,7.3,NaN,16.0,28.0,1.61,285.0,34.0,71.0,252.0,NaN,1.1,NaN,10.2,0.027945
97,Sugar cane,795984.0,59334059.0,380.0,0.00,98.1,0.00,0.0,NaN,NaN,NaN,NaN,1.0,83.0,NaN,133.0,9.0,4.0,28.0,1.20,1.2,NaN,NaN,0.000000
31,"Coffee, green",629300.0,165712.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Wheat,586543.0,3244062.0,340.0,13.21,72.0,2.50,10.7,9.0,1.9,NaN,5.0,44.0,34.0,3.60,363.0,137.0,357.0,2.0,2.60,61.8,4.06,64.0,0.175342
9,Barley,357994.0,964083.0,354.0,12.48,73.5,2.30,17.3,22.0,2.2,NaN,4.6,19.0,33.0,3.60,452.0,133.0,264.0,12.0,2.77,37.7,1.94,NaN,0.000000
64,Oranges,329561.0,4736715.0,47.0,0.00,11.8,0.00,2.4,225.0,NaN,53.2,NaN,30.0,40.0,NaN,181.0,10.0,14.0,NaN,NaN,NaN,NaN,37.0,0.101370
52,"Mangoes, mangosteens, guavas",215982.0,2396675.0,60.0,0.00,15.0,0.00,1.6,1082.0,4.2,36.4,NaN,43.0,11.0,NaN,168.0,10.0,14.0,1.0,NaN,NaN,NaN,NaN,0.000000
7,Avocados,215942.0,2300889.0,160.0,2.00,8.5,14.66,6.7,146.0,21.0,10.0,1.7,81.0,12.0,NaN,485.0,29.0,52.0,7.0,NaN,NaN,NaN,8.0,0.021918

We compare the 10 crops with the major production, the 10 with the major occupied area, and the 10 with the most interrelated. Also, we include the nutritional information for each set, considering portions of 100gr. However, only between maize and wheat the daily ingestion in Mexico per capita overcome 1-kilogram, and beyond defining a portion, we expect to create awareness in our food selection, because in this comparison, we do not include the food of animal origin, which represent high portions of protein and fats. Even for a vegetarian-style life, we should consider a better selection of foods.